


const ADD_ARTICLE = "ADD_ARTICLE";
const DATASHOW = "DATASHOW"
const MODAL = "MODAL"
const TOTAL_TABLE = "TOTAL_TABLE"
const STATUS_TABLE = "STATUS_TABLE"
const DATA_SELECTED = "DATA_SELECTED"
const INDEX_SELECTED = "INDEX_SELECTED"
const ISSHOW_MODAL = "ISSHOW_MODAL"
const TITLE_MODAL = "TITLE_MODAL"
const METHOD_MODAL = "METHOD_MODAL"
const DATA_MODAL = "DATA_MODAL"
const ADD_FILTER = "ADD_FILTER"
const UPDATE_FILTER = "UPDATE_FILTER"
const REMOVE_FILTER = "REMOVE_FILTER"

export {ADD_ARTICLE, DATASHOW, TOTAL_TABLE, 
    INDEX_SELECTED,DATA_SELECTED, ISSHOW_MODAL, TITLE_MODAL, METHOD_MODAL,
    STATUS_TABLE, DATA_MODAL, ADD_FILTER, REMOVE_FILTER, UPDATE_FILTER }