


const ADD_ARTICLE = "ADD_ARTICLE";
const DATASHOW = "DATASHOW"
const MODAL = "MODAL"
const TOTAL_TABLE = "TOTAL_TABLE"
const STATUS_TABLE = "STATUS_TABLE"
const DATA_SELECTED = "DATA_SELECTED"
const INDEX_SELECTED = "INDEX_SELECTED"
const ISSHOW_MODAL = "ISSHOW_MODAL"
const TITLE_MODAL = "TITLE_MODAL"
const METHOD_MODAL = "METHOD_MODAL"
const DATA_MODAL = "DATA_MODAL"
const ADD_FILTER = "ADD_FILTER"
const UPDATE_FILTER = "UPDATE_FILTER"
const REMOVE_FILTER = "REMOVE_FILTER"
const ADD_DATE_FILTER = "ADD_DATE_FILTER"
const REMOVE_DATE_FILTER = "REMOVE_DATE_FILTER"
const RESET_INDEX_SELECTED = "RESET_INDEX_SELECTED"
const RESET_DATA_SELECTED = "RESET_DATA_SELECTED"
const LOAD_DATA = "LOAD_DATA"
const LOADING = "LOADING"
const REMOVE_RECORD_TABLE = "REMOVE_RECORD_TABLE"
const SET_DATA_TAB_PANE = "SET_DATA_TAB_PANE"


export {ADD_ARTICLE, DATASHOW, TOTAL_TABLE, 
    INDEX_SELECTED,DATA_SELECTED, ISSHOW_MODAL, TITLE_MODAL, METHOD_MODAL,
    STATUS_TABLE, DATA_MODAL, ADD_FILTER, REMOVE_FILTER, UPDATE_FILTER ,
    RESET_DATA_SELECTED, LOADING,
    RESET_INDEX_SELECTED, LOAD_DATA,REMOVE_RECORD_TABLE,SET_DATA_TAB_PANE
    , REMOVE_DATE_FILTER, ADD_DATE_FILTER}